apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      run: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - name: mongodb
        image: dedsec995/mongodb:v1
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}